define metTomcio = False
define rudeToTomcio = False

label t_goingHomeFirstNight:
    "Decydujesz, że ci się nie chce, więc idziesz do swojego nowego domu."
    "Czujesz dreszcze przebiegające cię po plecach."
    "Ale{w=0.6} nie wiesz dokładnie, co je spowodowało - to, że nie ma żywej duszy{w=0.6}, czy to, że po prostu jest zimno."
    you "{i}Boże czemu jest tak zimno???{/i}"
    "Łapiesz się za ramiona próbując się jakoś ogrzać."
    you "{i}Jaka to pora roku?{/i}"
    you "{i}Czy oni w ogóle mają tu zimy?{/i}"
    you "{i}Chyba, że to jest wiosna...{/i}"
    you "{i}Nie chcę zimy!{/i}"
    "Mówiąc to, tupnąłeś nóżką jakbyś wino robił."
    "Patrzysz się w górę w poszukiwaniu odpowiedzi, ale widzisz tylko ciemne, puste i nudne niebo."
    "Jedyny fakt o tym mieście, którego jesteś w 100%% pewien, to jest to, że fontanna jest magiczna."
    "Podchodzisz więc bliżej, żeby jej się lepiej przyjrzeć..."
    
    scene bg fountainnight with dissolve
    stop music fadeout 10.0
    play sound "sfx_footsteps_a.mp3"

    "Im bliżej jesteś do tej fontanny, tym ciszej się robi..."
    "Nie, że wcześniej było głośno w środku nocy."
    "Tylko, że wtedy słychać było wiatr w koronach drzew, żarzące się latarnie na ulicach, szum przelatujących ptaków, ale teraz {b}wszystko{/b} ucichło..."
    "Wszystko oprócz szumu wody w fontannie, który z sekundy na sekundę staje się coraz bardziej uciążliwy i głośniejszy."
    "Powietrze jest gęste i ciężkie, a ty czujesz to wyraźnie..."
    "Nic się nie dzieje. Stoisz tam przez dłuższą chwilę, ale sytuacja nie nabiera tępa i znudziło ci się czekanie, więc postanawiasz wrócić do domu."
    "Wygląda na to, że będziesz musiał wrócić tutaj później."
    "Oddalasz się od fontanny i idziesz do domu."
    scene bg colacocastreetnighta with dissolve
    play music "town_night.mp3" fadeout 10.0
    play sound "sfx_footsteps_b.mp3"
    you "{i}Gdzie ja w ogóle mieszkam?{/i}"
    "Patrzysz na klucz w swojej dłoni."
    "Do klucza jest przypięty mały breloczek, na którym jest napisane ul. króla Aszurnasirpala II."
    "Dzięki plot armor nie masz problemu ze znalezieniem ulicy z breloczka."
    "Na jej długości są tylko trzy domy, a ten na samym końcu jest twój."

    menu:
        "Chcę się przywitać":
            you "Nie chce wyjść na niemiłego, muszę się przywitać."
            "Podchodzisz do pierwszego lepszego domu..."
            you "{i}Czemu ma zamkniętą bramę?{/i}"
            you "{i}Czy to dla mnie zbudowano taki tor przeszkód?{/i}"
            you "{i}Co to ma być? Wipeout?{/i}"
            "Na szczęście jesteś skinny więc po prostu wsadzasz rękę przez pręty bramy i otwierasz ją od środka." 
            "Ale plot armor nie jest taki duży, więc ręka utyka ci w ogrodzeniu. Na szczęście po kilku sekundach ciągnięcia udaje ci się ją wyciągnąć."
            "Gdyby ktoś cię teraz zobaczył, to byś stracił tyle aury..."
            "Próbujesz nonszalancko zamknąć za sobą bramę, ale po przejściu kilku kroków się otwiera."
            you "{i}Głupia brama!{/i}"
            you "{i}Pff... to już nie mój problem{/i}"
            "Dom tego sąsiada jest strasznie nudny, a brak jakichkolwiek roślin w około budynku nie poprawia tej sytuacji."
            "Podchodzisz do drzwi i pukasz do drzwi ― tak samo jakbyś szedł na rozmowę o pracę ― i czekasz."
            "Nikt nie otwiera, więc pukasz jeszcze raz, a dokładniej 3 razy."
            "Znowu nikt nie otwiera..."
            "Zdecydowałeś, że to jednak nie był najlepszy pomysł, żeby robić meet & greet z sąsiadami w nocy. Z tego powodu odwracasz się, żeby odejść, ale słyszysz za sobą ciche skrzypnięcie."
            you "{i}Co to było?!{/i}"
            "Postanawiasz zignorować ten dźwięk i kontynuować podróż do swojego domu."
            "Ale nagle czyjś głęboki i gardłowy głos sprawia, że podskakujesz ze strachu."
            m "Czy mogę ci w czymś pomóc??"
            you "AAAAA!!!"
            #TODO: (S)creaming sound
            "w oka mgnieniu odwracasz się i widzisz sąsiada, którego chciałeś odwiedzić ― jeszcze zaspanego."
            show tomcio normal with dissolve
            "Gość jest zbudowany jak byk (i to tak dosłownie) ― wysoki i szeroki."
            you "{i}Whoopsie daisy yoo hoo{/i}"
            you "{i}...{/i}"
            you "{i}No i co mam teraz zrobić???{/i}"
            you "{i}Będę chyba nonchalant.{/i}"
            you "Nie strasz tak ludzi, to bardzo niegrzeczne!"
            m "???"
            m "To nie {b}ty{/b} przypadkiem pukałeś {b}mi{/b} do drzwi i to w {b}środku nocy{/b}???"
            m "Jaki jest powód takiego ― nie ukrywajmy ― niemiłego najścia?!"
            you "No dobra, powiedzmy że masz rację.."
            "Sąsiad jest oszołomiony twoją arogancją i zaczyna patrzeć na ciebie jak spod byka."
            you "Jestem twoim nowym sąsiadem i chciałem się przywitać."
            you "Przepraszam, że chciałem być miły!"
            m "No to cześć?"
            you "{i}Za kogo on mnie ma że tak się do mnie odzywa!{/i}"
            you "Czy to wszystko???"
            m "Ale o czym chcesz gadać, jest prawie północ!!!"
            menu:
                "Zapytaj kim on jest":
                    $ metTomcio = True
                    you "Kim jesteś?"
                    t "Nazywam się Tomcio."
                    you "I to tyle???"
                    you "Opowiedz coś więcej o sobie, np. czym sie zajmujesz."
                    "Tomcio pochylił się bliżej ciebie i popatrzył się na ciebie jeszcze bardziej podejrzliwie niż wcześniej."
                    t "A po co ci ta informacja?"
                    you "{i}Ale dał do pieca...{/i}"
                    you "{i}I zatkało mi kakao...{/i}"
                    you "{i}Aha! {w=0.6}Wiem! {w=0.6}Teraz wszystko wiem! {w=0.6}Wiem jak na to odpowiedzieć! {w=0.6}Wiem wiem wiem! {w=0.6}Eureka!{/i}"
                    you "Chcę się upewnić, że moi sąsiedzi nie szponcą nieleganie."
                    t "Nigdy w życiu nie słyszałem {b}tak{/b} oburzającego stwierdzenia!!!"
                    t "No ale skoro musisz wiedzieć... to pracuję dla rządu."
                    you "Aha, ok."
                    you "Ale nudna praca. Myślałem że coś ukrywasz."
                    you "No to dziękuję ja idę spać."
                    you "DOBRANOC!"
                    hide tomcio normal with dissolve
                    you "{i}Ten tomcio to chyba spoko gość, tylko trochę dziwny. No cóż sąsiadów się nie wybiera, przeżyję.{/i}"

                "Opowiedz mu wszystko o sobie":
                    you "Dobry wieczór."
                    m "Raczej dobranoc!"
                    you "Dobry―a... {w=0.3}noc???"
                    you "Jak pan się nazywa?"
                    you "Yyy... {w=.3}w każdym razie nie ważne. Ja będe pierwszy!!!"
                    you "Pewnie się domyślasz, ale jestem twoim sąsiadem i jestem bardzo szczę..."
                    "On robi krok do tyłu i zamyka ci drzwi przed nosem."
                    hide tomcio normal with vpunch
                    play sound "sfx_door_slam.mp3"

                "Ragebait":
                    $ rudeToTomcio = True
                    you "A w sumie, nie ważne."
                    "Obracasz się na pięcie i zaczynasz uciekać, podskakując."
                    m "CZEKAJ!!!"
                    m "Boże święty...{w=.6} czemu ty ode mnie uciekasz???"
                    m "Czy ja naprawdę...{w=.6} jestem taki groźny???"
                    m "Czy to przez to{w=.6}, że jestem gruby???"
                    "On wpada w malignę, zaczyna płakać i zamyka drzwi."
                    hide tomcio normal with dissolve
                    you "{i}???{/i}"
                    you "Nie mam {b}ZIELONEGO{/b} pojęcia co się właśnie stało, chyba pora na sen."
            "Wychodzisz przez bramę, spoglądając przy tym przez ramię by upewnić się, że sąsiad cie nie goni i idziesz do domu."
        "Chcę iść spać":
            you "Zmęczyłem się"
            "Czym niby??? Ale ok."
    "Dom był niedaleko, więc szybko trafiłeś pod drzwi swojego nowego lokalu."
    "Nie wyglądał on przytulnie, ale teraz jest za późno na takie rozmyślania."
    jump h_wakingUpAfterFirstNight


label t_goingIntoTownFirstNight:
    "Odwracasz się w stronę urzędu miasta i widzisz ogromne jezioro w tle."
    "Ta woda na choryzoncie jest całkiem przejrzysta, prawie jak w basenie."
    "Potem patrzysz w bok i widzisz tę nieodkrytą część małego miasteczka Bratgren."
    "Gdzie ty chcesz iść?"
    menu:
        "JEZIORO!!!":
            jump l_firstNightLakeVisit
        "MIASTO!!":
            jump t_firstNightTownWalk

define hasToApologiseToPiotr = False
define metWiktoriaP = False
define receivedLoreAboutChurchOnTheFirstDay = False
label t_firstNightTownWalk:
    $ receivedLoreAboutChurchOnTheFirstDay = True
    you "{i}Możę znajdę tu coś ciekawego do zwiedzenia. Ten rynek wydaje się być trochę pusty, ale może mnie czymś zaskoczy.{/i}"
    "Rozglądasz się po rynku i próbujesz wyobrazić sobie ten coroczny festiwal właśnie tutaj na rynku."
    "Barbara nie powiedziała ci, czym właściwie jest ten festiwal, ani co ludzie wtedy robią, ani nawet czego on dotyczy, więc ta tradycja pozostaje tajemnicą, którą dopiero masz odkryć."
    "Rozglądasz się i zauważasz fontannę, poza którą na rynku nie ma nic."
    "Widzisz kościół w oddali i postanawiasz się mu przyjrzeć."
    scene bg churchnighta with dissolve
    "Gdy już postanawiasz spuścić wzrok z tego pięknego zabytku architektury, widzisz...{w=.1} kogoś."
    you "{i}W KOŃCU!{/i}"
    you "{i}Pierwszy raz widzę kogoś na tej ulicy.{/i}"
    "Nie jesteś pewien czy chcesz do tej osoby podejść i porozmawiać czy raczej unikać."
    you "{i}Mam nadzieję, że mnie nie ten ktoś nie pobije.{/i}"
    "Aż w końcu tajemnicza osoba macha do ciebie i gestem zachęca abyś podszedł bliżej."
    you "{i}Czego onx chce???{/i}"
    "Podchodzisz bliżej do tajemniczej sylwetki przed kościołem, zachowując przy tym wszystkie środki bezpieczeństwa."
    show wp normal with dissolve
    you "Dobry wieczór...?"
    m "Czy my się znamy?"
    you "Nie wydaję mi się."
    m "Ty nie pracujesz przypadkiem po drugiej stronie miasta?"
    you "No nie, bo jestem tutaj nowy!"
    m "Aha."
    m "No to cześć."
    you "..."
    m "..."
    you "..."
    $ metWiktoriaP = True
    wp "Mam na imię Wiktoria."
    you "Miło cię poznać! Mam na imię [name]."
    "Uśmiechasz się jak w reklamie nieruchomości."

    $ newName = name.strip().split(" ")[0].lower()#  "Dupa 3.0" -> "dupa"

    wp "No właśnie miałam mówić, że wyglądasz na [newName]."
    wp "Masz fajne imię."
    wp "[name] [name] [name]"
    "Rzucasz jej surowe spojrzenie ― niemalże piorunujesz ją wzrokiem."
    wp "Skoro już tu jesteś to mogę równie dobrze opowiedzieć ci coś o tym mieście."
    "Wiktoria otwiera bramę przed kościołem, żeby umożliwić ci bliższe obejźrnięcie."
    "Zrobiłeś tylko 3 kroki do przodu, więc twój widok niewiele się zmienił."
    "(Czego się spodziewałeś?)"
    wp "Wiesz, że Bjork jest założycielką naszego miasta?"
    you "No tak, kurowska mi o niej mówiła. Założyła nasze miasto jakieś czterysta lat temu."
    wp "Nie do końca. Bjork założyła nasze miasto 399 lat temu a 400 rocznica będzie obchodzona podczas tegorocznych zielonych świątek."
    you "Wow! Ale heca."
    wp "No rel. Bjork to islandzka podróżniczka która to wszystko zaczęła."
    wp "Była zwykłą kobietą ― jak większość kobiet tutaj w bratgren."
    wp "Pewnego dnia Bjork obudziła się i miała wizję, w której pojawiła się dusza, która coś jej tam wyszeptała."
    "Wiktoria wskazuje na witraż. Patrzysz na niego i dopiero z tą narracją uświadamiasz sobie, że to duch."
    "Wpatrujesz się w witraż próbując obejrzeć go pod różnymi kątami."
    wp "Czy coś jest nie tak?"
    you "Nie, nie to nic."
    wp "Bjork zrobiła ten witraż swoimi rękami."
    you "Aha teraz ma sens czemu jest taki..."
    "Patrzy sie na ciebie jakbyś właśnie zabił starą lichwiarkę i jej siostrę."
    "{i}Może lepiej nie obrażać ich wierzeń...{/i}"
    with vpunch
    # TODO: *gulp* - dodaj dźwięk a nie takie chyry byry mi tutaj robisz
    you "...{w=.3} Tzn ma taki...{w=.6} unikalny styl ― nigdy wcześniej czegoś takiego nie widziałem."
    wp "{b}No ja myślę!{/b}"
    wp "Ale wracając, nikt nie wie co ta dusza tam wyszeptała do Bjork, a ten witraż to jedyna interpretacja szeptu jaką mamy."
    wp "Po spotkaniu z tą duszą jej serce wypełniło się determinacją, więc poszła szukać miejsca z najlepszym vibem."
    wp "Bjork dużo pisała w swoim dzienniku."
    wp "Pierwsze co napisała to \"If travel is searching, and home what's been found, im not stopping.\""
    wp "Zaczęła podróżować po całym świecie w poszukiwaniu idealnego miejsca na miasto."
    you "Wow! Ale diva."
    wp "No rel ona była taką {b}final girl{/b}."
    you "Ej, rell."
    wp "A wiesz co po tych podróżach zrobiła?"
    you "Nie."
    wp "Ale to było pytanie retoryczne..."
    "-1000 aury!"
    you "No dobra mów już!"
    wp "Szła tu gdzieś przez las, gdy poczuła taki mega fajny vibe."
    wp "Zorientowała się od razu, że ten vibe był lepszy niż wszystkie i od razu wiedziała że to miejsce nadaje się na miasto."
    wp "Ale ostatnio ta tarcza osłabła i czarodzieje tacy jak Piotr muszą pomagać nam chronić Bratgren."
    #TODO: plot hole
    you "Właśnie obudziłem się pierwszy raz tutaj obok Piotra, jak robił jakiś rytuał."
    wp "Serio?"
    you "Noooo!"
    you "Od razu myślałem, że to jego wina i wgl masakra z nim."
    you "Ale chyba jest spoko..."
    wp "No fajny jest on wszystkim pomaga."
    you "Weź bo teraz wyszedłem na niemiłego..."
    wp "No to przeproś go?"
    $ hasToApologiseToPiotr = True
    you "No, no przeproszę..."
    you "No ale dobra, wracając do tej Bjorkowej."
    you "Ona to miasto sama zbudowała?"
    wp "Nie no, oczywiście, że nie."
    wp "Po pierwsze, wtedy miasto było dużo mniejsze. Minęło w końcu czterysta lat, trochę się rozrosło."
    wp "A po drugie, nie była sama..."
    you "OKEJ...??"
    wp "Była jeszcze{w=.3} Sabrina Carpenter."
    "Nie wiesz czemu, ale to imię brzmi znajomo, chociaż nikt nigdy ci go nie wspominał."
    "To bardzo dziwne i cię trochę niepokoi."
    you "{i}Gdzieś to imię już słyszałem...{/i}"
    you "{i}Czemu ja ją kojarzę?{/i}"
    you "{i}Chyba jest ważna!{/i}{nw}"
    wp "Halo, czy ty mnie w ogóle słuchasz?"
    you "Yyy... tak, tak mów."
    wp "A więc to była najlepsza przyjaciółka Bjork i też jakby ironicznie cieśla."
    wp "Zbudowały kilka domów i ludzie zaczęli się pojawiać ― tak jak ty."
    wp "I tak w ogóle to do dziś nie wiadomo skąd ci ludzie się biorą."
    you "Nawet Bjork nie wiedziała?"
    wp "No{w=.3} nie."
    wp "A teraz plot twist! Zgadnij jak ona umarła..."
    you "Została łysa?"
    wp "Co?{w=.3} Nie?"
    wp "Jej śmierć była {b}BARDZO{/b} tragiczna."
    wp "Była prezydentem tylko 23 lata kiedy sabrina ją zdradziła i dźgnęła nożem!!!"
    you "{i}A teraz {b}mi{/b} jest łyso, bo nie wiedziałem tego faktu.{/i}"
    you "{i}Wiedziałem, że sabrina jest ważna!!!{/i}"    
    wp "Zginęła w aktualnym biurze kurowskiej. Dokładnie tam, gdzie ona teraz siedzi."
    wp "Ostatnie słowa Bjork były \"I thought I could organize freedom. How scandinavian of me...\""
    wp "To był tragiczny dzień dla całego miasta i od tamtej pory co rok duchy powstają z martwych."
    you "{i}Mam tyle pytań...{/i}"
    jump t_firstNightTownWalkQuestionsMenu

define askedAboutSabrina = False
define askedAboutBjorkDeath = False
define askedAboutGhostsTalking = False
label t_firstNightTownWalkQuestionsMenu:
    if askedAboutSabrina and askedAboutBjorkDeath and askedAboutGhostsTalking:
        jump t_afterFirstNightTownWalkQuestionsMenu

    menu:
        "Co się stało z sabriną" if not askedAboutSabrina:
            $ askedAboutSabrina = True
            wp "Ona była w gorącej wodzie kąpana po tym jak zabiła Bjork..."
            wp "W sensie nie było wody, a tylko temperatura{w=.6} ― została spalona na stosie."
            you "Ej szczerze ― też bym ją spalił za to."
            wp "No, rel!"
            you "No, ale czekaj..."
            you "Czemu Sabrina ją zdradziła???"
            wp "Nikt nie wie."
            wp "Ale chyba była delulu."
            you "{i}Czemu nikt w tym mieście nie pamięta {b}NAJWAŻNIEJSZYCH{/b} rzeczy z historii, to jest takie dziwne...{/i}"
            jump t_firstNightTownWalkQuestionsMenu
        "Jak umarła Bjork" if not askedAboutBjorkDeath:
            $ askedAboutBjorkDeath = True
            wp "Bjork była z Islandii, no co nie?"
            you "Mnie się pytasz?!"
            wp "Dobra nie ważne!"
            wp "No to chcieliśmy uczcić tradycje tego kraju kiedy ona umarła."
            wp "Ciało Bjork zostało położone na łodzi, którą wypuszczono na wyjątkowo spokojne jezioro Świtezianka."
            you "Czemu położyliście ją na łódzi."
            wp "Jezu czy ty mnie słuchasz...{w=.3} Mówiłam, że takie są tradycje!"
            you "No, dobra już...{w=.3} I to wszystko?"
            wp "A no tak ― zapomniałam najważniejszej rzeczy!"
            wp "Ogólnie mieliśmy podpalić tę łódkę, ale jakaś siła wciągnęłą ją pod wodę..."
            you "Jak można o czymś takim zapomnieć???"
            jump t_firstNightTownWalkQuestionsMenu
        "Czy mogę rozmiawiać z tymi duchami" if not askedAboutGhostsTalking:
            $ askedAboutGhostsTalking = True
            wp "PO PIERWSZE...{w=.6} To nie są duchy tylko dusze ― wkurzą się jeśli nazwiesz je duchami."
            you "{i}Duchy i dusze to prawie to samo. Przecież mnie nie ukrzyżują jak ich zmisgenderuje...{/i}"
            you "Ups, przepraszam nie wiedziałem."
            wp "Nic się nie dzieje..."
            wp "I tak, możesz z nimi rozmawiać, ale tylko podczas tego festiwalu."
            wp "A właściwie to one mogą mówić tylko przez te siedem dni."
            wp "Jednak nie bój żaby ― bo możesz je zobaczyć przez cały rok ― ale nie będą cię nawiedzać."
            jump t_firstNightTownWalkQuestionsMenu

define fountainLoreReceived = False
label t_afterFirstNightTownWalkQuestionsMenu:
    you "Czy jest coś jeszcze, co powinienem wiedzieć?"
    wp "Tak, zapomniałam ci powiedzieć, czemu w ogóle opowiadam ci o tym kościele."
    you "Słucham?"
    wp "W tym kościele jest mnóstwo relikwii.{w=.3} Na przykład nóż, którym zabito Bjork."
    wp "Teraz jest zamknięty, ale jeśli kiedyś będziesz potrzebować odpowiedzi, znajdziesz je tutaj."
    you "Aha, dobra, dzięki."
    "Opuszczasz teren kościoła, a Wiktoria zamyka za tobą bramę."
    "Zrobiłeś tylko 3 kroki do tyłu więc twój widok niewiele się zmienił."
    "(Czego się spodziewałeś?)"
    you "To tyle informacji naraz..."
    you "Na pewno do jutra wszystko zapomnę."
    wp "Ej, rell!!!"
    wp "Tak szczerze, sama nie wiem jak ja to pamiętam."
    wp "W każdym razie, jeśli będziesz czegoś potrzebować, jestem tu, żeby pomóc."
    you "Aww, dziękuję."
    you "Dobra to teraz mi powiedz, która jest godzina?"
    wp "No jest już po północy."
    you "Czemu ty łazisz an rynku po północy???"
    wp "Yyyy...{w=.6} Nie interesuj się!"
    you "{i}SUSPICIOUS BEHAVIOUR{/i}"
    you "Myślę, że najlepiej już pójdę do domu. Jeszcze go nawet nie widziałem."
    wp "Czekaj, jaki dom???{w=.6} Skąd???"
    you "Dom{w=.6}, który dostałem od Kurowskiej?"
    wp "CO?"
    wp "Jak to dostałeś, dom???"
    "Pokazujesz jej klucze, które się okazują mocno spocone od twojej ręki."
    you "No, od Kurowskiej dostałem."
    wp "Czemu ona teraz magicznie ma swoich ulubieńców?"
    you "Może mi ktoś wytłumaczyć, co się dzieje???"
    wp "Kurowska zwykle nie rozdaje domów za darmo."
    you "To nie było za darmo, powiedziała, że muszę znaleźć pracę."
    wp "Aaaa, ona trochę nie lubi bezrobotnych."
    wp "Cokolwiek robisz, pamiętaj, żeby płacić podatki. Wtedy będziesz miał z nią spokój."
    wp "Jest miła tylko dla tych, co je płacą."
    you "Oho, okej."
    you "Dziękuję ci za wszystkie informacje, bardzo to doceniam, ale teraz chciałbym się położyć."
    you "Dobranoc."
    wp "Pa."
    $ fountainLoreReceived = True
    scene bg citysquarenight with dissolve
    "Zaczynasz iść do domu. Głowa ciąży ci od nadmiaru informacji, które właśnie otrzymałeś."
    "Z wiązku z ciężkim dniem, nie myślisz nad niczym innym niż snem. Z tego powodu od razu kładziesz się spać."
    jump h_wakingUpAfterFirstNight

# renpy-graphviz: BREAK


label t_goingToTownToKurowskaDueToHungerDayTwo:
    scene bg citysquareday with dissolve
    play music "town_day.mp3"
    play sound "sfx_footsteps_b.mp3"
    "Idąc do Kurowskiej, podziwiasz budynki i przyrodę, ponieważ dzień wcześniej nie dało się tego zrobić."
    "Droga do urzędu miasta była bardzo przyjemna, jednak najgorszą częścią było zignorowanie zapachów wydobywających się z piekarni."  
    "Brzuch ci burczy, niestety nie masz żadnych pieniędzy by zapłacić za potencjalny posiłek."
    you "{i}NIE WYTRZYMAM... taki jestem głodny. Trzeba było wczoraj pożyczyć od kogoś pieniądze. No cóż, muszę jeszcze wytrzymać do końca dnia, aż otrzymam moją dzisiejszą wypłatę.{/i}"
    "{i}Albo może zapiszą mi ten bułę na kreskę, a ja zapłacę za nią później... Chociaż ta praktyka zniknęła ż PRL-em... Dobra dam radę!!! Kto jak nie ja?{/i}"
    "Ulice teraz tętnią życiem, każdy spieszy się do pracy, w niektórych momentach nawet ciężko przecisnąć się przez tłumy."
    "Jednak nikt nie odważy się zbliżyć do fontanny."
    "Patrzysz w górę i dziwisz się, że dalej nie widać słońca."
    "Ludzie są prawdopodobnie przyzwyczajeni do niekończących się chmur stratus, pokrywających niebo."
    "Gdy podchodzisz do urzędu, on znowu robi na tobie wrażenie, nie tak wielkie jak wczoraj, ale dalej jest bardzo inponujący."
    "Nie ma czasu do stracenia i wchodzisz do budynku, szukając Filipa."
    jump ch_goingToTownToKurowskaDueToHungerDayTwoPartTwo

# renpy-graphviz: BREAK

define workedAtVasili = False
define workedAtFilip = False

# renpy-graphviz: BREAK
label t_goingToFindAJob:
    scene bg citysquareday with dissolve
    play sound "sfx_door_open.mp3"
    "Wychodzisz na zewnątrz, żeby zastanowić się co powinieneś zrobić dalej."
    "Jak powiedziała Kurowska, powinieneś wybrać kogoś kogo znasz i pójść do niego, żeby poprosić o pracę."
    "Stoisz na rynku i rozglądasz się, jakbyś miał całować ziemie, trzymając cyprysowy krzyżyk."
    "Ponieważ nie chcesz dzisiaj umrzeć z głodu. Do kogo idziesz pracować?"
    menu:
        "Vasili (to jest ta ciekawsza opcja)" if metVasili:
            you "{i}Pójdę do niego tylko dlatego, że jestem ciekaw.{/i}" 
            you "{i}Poza tym chyba nie mam lepszej opcji.{/i}" 
            $ workedAtVasili = True
            jump l_workingAtVasili
        "Filip":
            you "{i}Kurowska nie ma dla mnie roboty, ale Filip już może mieć.{/i}" 
            $ workedAtFilip = True
            jump ch_workingAtFilip
    
label t_gotMoney:
    scene bg citysquareday with dissolve
    "Masz dość bycia głodnym, więc idziesz prosto do BBB."
    "(Big Buły Bakery)"
    jump t_gotMoneyBakeryEntrance

label t_gotMoneyBakeryEntrance:
    scene bg bakeryfrontday with dissolve
    play sound "sfx_footsteps_b.mp3"
    "Piekarnia jest rzeczywiście duża. Zapachy rozchodzące się po ulicy doprowadzają cię do szału."
    "Zapach drożdży unosi się w powietrzu, a za szybą jest wiele wypieków."
    scene bg bakeryinside with dissolve
    play sound "sfx_footsteps_a.mp3"
    "Pierwsze co zauważasz w środku to plakaty Taylor Spit."
    "Ale{w=0.5}.{w=0.5}.{w=0.5}.{w=0.5}.{w=0.5}.{w=0.5}.{w=0.5}.{w=0.5}.{w=0.5}. Jest kolejka."
    show wp normal at leftish with moveinleft
    show fraucrusty normal at center with moveinleft
    show rafal normal at rightish with moveinright
    "Przed tobą są dwie osoby."
    "Pierwszą w kolejce jest Frau Crusty."
    if metWiktoriaP:
        you "O, hej."
        wp "No cześć! Co tam?"
        
        if workedAtFilip:
            you "Masakra... Musiałem pracować..."
            wp "Do kogo poszedłeś?"
            you "Do Filipa."
            you "Kazał mi przenosić dokumenty do Kurowskiej."
            you "A jak już skończyłem, Kurowska kazała mi z powrotem przenieść te listy."
            you "Bo to on ma je czytać."
            wp "Trzeba było zarządać pieniądzy i wyjść po czymś takim."
            wp "I skibidi."
        elif workedAtVasili:
            you "Masakra... Musiałem pracować..."
            wp "Do kogo poszedłeś?"
            you "Do Vasiliego."
            if endorsedCommunism:
                you "Wiesz co, nie było źle."
                you "Mamy lekko podobne poglądy polityczne."
                "Wiktoria robi bombastic side eye."
            else:
                you "Jezu, to była masakra, cały czas o komuniźmie gadał."
            you "Szkoda gadać."
            you "Ty go znasz lepiej ode mnie, pewnie wiesz jak to wyglądało."
            wp "Let me guess."
            wp "Śpiewał \"Międzynarodówkę\"?"
            you "Tak..."
            wp "Współczuję..."
        else:
            you "Czaisz, że dostałem pieniądze od Kurowskiej"
            wp "Tak o??"
            you "No tak!"
            you "Tak o."
            wp "Nie za dobrze ci?"
            you "Nie."
    else:
        "Natomiast, zaraz przed tobą jest Wiktoria P."
    jump t_gotMoneyBakeryCustomer

label t_gotMoneyBakeryCustomer:
    frau "A cóż to za bezczelne pytanie?"
    frau "Oczywiście, że mam pieniądze."
    frau "Tylko dzisiaj brakuje mi 23 foryntów."
    frau "Mogę je przynieść jutro???"
    m "No nie jestem bankiem. To tak nie działa. Nie wydam tego tortu jeśli ktoś za niego nie zapłaci."
    frau "Ale mam dzisiaj urodziny!!!"
    menu:
        "Daj jej trochę monet":
            you "Masz."
            frau "Mój gyatt tutaj utknie na dobre!"
            frau "Dziękuję Ci dobry furasie."
            with vpunch
            show fraucrusty normal at offscreenleft with move
            "Frau Crusty wychodzi z piekarni z tortem skipem C."

        "Udawaj, że nic nie słyszałeś":
            frau "Wszyscy jesteście bezczelni i agresywni."
            with vpunch
            show fraucrusty normal at offscreenleft with move
            "Frau Crusty wychodzi z piekarni bez tortu skipem C."
    hide fraucrusty
    jump t_gotMoneyBakeryTea

label t_gotMoneyBakeryTea:
    wp "Okeeej."
    m "Hejka."
    wp "No cześć, co tam?"
    m "A w sumie nic, w malignie byłem cały dzień."
    wp "Tak standardowo bym powiedziała."
    "Oboje zaczęli się śmiać."
    wp "Poproszę 3 buły Rafała."
    m "Jasne."
    "Z tyłu widać całe koszyki z bułami Rafała."
    "Patrzysz się na te buły jak na monoporcje z Los Angeles."
    "Tylko, że buły Rafała nie kosztują $15 za 150g."
    "Nie masz zielonego pojęcia jaka to waluta jest w tym mieście ― pierwszy raz się z nią spotykasz."
    "Niby coś tam masz, ale nie wiesz czy tego starczy na jedną bułę, czy sto."
    you "{i}Te buły są tutaj mega popularne.{/i}"
    you "{i}Ale bym zjadł taką..{/i}"
    m "Proszę."
    "Nagle wchodzi kolejny nieznany ci mężczyzna."
    "Wygląda jak jakiś alfons."
    show niuniu normal at leftish
    show wp normal at rightish
    show rafal normal at right 
    with move
    m "Jezu, to znowu ty."
    m "Tak, Rafale, to ja!"
    r "No co ty chcesz ode mnie znowu?"
    m "Pokaż, co masz pod kapeluszem."
    "Wiktoria zaczyna mówić do ciebie szeptem, żeby nie ściągnąć na siebie uwagi."
    wp "To jest Niuniu."
    wp "To jest taki typ, co wymyśla teorie spiskowe w tym mieście."
    wp "I tym razem ofiarą jest Rafał."
    wp "On był na koncercie Taylor Spit i podczas tego koncertu ona rzuciła w niego swoim kapeluszem."
    wp "Od tego dnia cały czas go nosi."
    wp "A Niuniu wymyślił, że on coś pod nim ukrywa."
    show rafal normal at center 
    show wp normal at rightish 
    with move
    r "Nie, dobra, mam dość."
    "Rafał wyciąga miotłę i uderza Niunia."
    with vpunch
    n "AAAAA"
    r "Sharp or dull"
    n "Sharp?"
    r "Nie. To jeszcze raz."
    with vpunch
    "Uderza go jeszcze raz."
    n "No, to jest sharp."
    r "Wyjdź z mojej piekarni, bo zaraz ci sharp or dull zrobię cegłą."
    n "Dobra, dobra."
    show niuniu normal at offscreenleft with move
    show wp normal at leftish with move
    show rafal normal at rightish with move
    you "Współczuję."
    you "Czy ty naprawdę masz tu gdzieś cegłę?"
    r "Tak. Jestem przygotowany."
    'Wyciągnął wielką, czerwoną cegłę obiema łapami i z dumą pokazał ją tobie, jakby była jego dzieckiem.'
    'Cegła była stara. Naprawdę stara.'
    'Już na pierwszy rzut oka dało się stwierdzić, że nie da się stwierdzić, ile dokładnie ma lat - liczne odpryski i rysy były na to dowodem.'
    'Właściwie była tak stara, że przypisanie jej jakiejkolwiek liczby wydawało się obrazą nie tylko dla cegły, ale i dla tego, kto ją stworzył.'
    "Nazwanie jej po prostu 'starą' oznaczałoby wymazanie stuleci, które przetrwała."
    'Cegła dawno straciła ostre krawędzie i stała się zaokrąglona, jakby była używana wielokrotnie.'
    'Jeden z rogów był szczególnie wytarty i nawet najmądrzejsza osoba w tym mieście nie potrafiłaby powiedzieć, dlaczego jest wyszczerbiony ani gdzie dokładnie jest ten róg.'
    'Tylko Rafał mógłby to wiedzieć - o ile wie albo pamięta, co się z nią stało.'
    'Jedynym zastosowaniem tej cegły było rzucanie, więc starasz się nie wyciągać pochopnych wniosków co do tego, kto będzie lub już był ofiarą.'
    'Patrząc na wyszczerbiony róg, staje się jasne, że to efekt pewnego powietrznego wydarzenia.'
    'Można by nawet uznać za cud, że cegła jeszcze nie pękła na pół.'
    "Że jeszcze nie pękła na pół, jak arbuz spadający na nóż z 100m w jakimś filmiku na youtubie"
    'Jej amorficzna porcelanowa struktura wciąż trzymała się mocno po tych wszystkich latach, czego nie da się powiedzieć o niektórych związkach.'
    'Cegła była na tyle stara, że mogłaby uchodzić za najstarszy obiekt na tej planecie - albo gdziekolwiek teraz jesteś.'
    'Nie wiesz dokładnie, gdzie jesteś, ale jedno jest pewne - ta cegła jest starsza niż ziemia, na której stoisz.'
    'Starość nie była już dla niej przymiotnikiem, tylko wrodzoną właściwością.'
    'Nieważne, gdzie Rafał dotyka cegły swoimi łapkami - osypuje się trochę kurzu i pokruszonej gliny, jakby cegła miała łupież.'
    'Rafał jednak całkowicie ignoruje bałagan, który właśnie zrobił, jakby był do tego przyzwyczajony.'
    'Ignoruje też pył na swoich miękkich łapkach, bo wie, że i tak zaraz schowa ten delikatny wyrób z gliny, więc nie ma sensu ich myć.'
    'W tym momencie każdy rozsądny człowiek przestałby myśleć o cegle.'
    'Ty jednak nie przestajesz.'
    'Jedna ze stron cegły była ciemniejsza od pozostałych - jakby była wystawiona na działanie warunków atmosferycznych, podczas gdy reszta spoczywała bezpiecznie w ścianie.'
    "Prawdziwi naukowcy mogliby poświęcić całe życie badaniu tej różnicy i nadal nie dojść do porozumienia."
    "Tak tajemnicza była ta cegła."
    'Nie da się stwierdzić, czy Rafał wyjął cegłę, czy sama wypadła.'
    'Można jednak zauważyć, że cegła {i}należy{/i} do tej piekarni, ze względu na swój charakterystyczny, ale już wyblakły, czerwony kolor, który był bardziej przygaszony niż reszta cegieł w tej piekarni.'
    'Przy bliższym spojrzeniu widzisz wszystkie jej niedoskonałości - ślady, które zostawił czas.'
    'Pęknięcia są wypełnione kurzem tak starym i tak głęboko osadzonym, że nawet woda nie jest w stanie tam dotrzeć.'
    'Stały się częścią kapsuły czasu, którą jest ta cegła.'
    'Ta cegła była prawdopodobnie starsza niż ty i znajdowała się w tym mieście długo przed twoimi narodzinami.'
    'Widziałeś przez nią setki, jeśli nie tysiące ludzi i miliony wypowiedzianych słów.'
    'Cegła zna wszystkie sekrety miasta, ale nie może mówić ani ujawnić prawdy.'
    'Miała też wyraźnie wyznaczone miejsce pod biurkiem Rafała, gdzie trzymał kasę i prowadził codzienny handel.'
    'Nie każdy klient wiedział - albo mógł nawet podejrzewać - istnienie tej cegły.'
    'Jeśli Rafał wyciąga ją przed tobą, oznacza to, że jesteś albo ofiarą, albo jego bliskim przyjacielem.'
    'Zauważasz też małe, wielokolorowe plamy rozsiane po jej powierzchni - każda inna, każda o innym kształcie, rozmiarze i własnej historii.'
    'Jedna może mieć dwa dni, a druga obok niej ponad dwa lata, bez żadnej możliwości odróżnienia.'
    'Bo w tym wszechświecie nie wynaleziono datowania radiowęglowego.'
    "Mimo pozornej przeciętności 'losowej cegły' nie możesz pozbyć się wrażenia, że w tej amorficznej strukturze zaklęte są codzienne sprawy mieszkańców miasta Bratgren."
    'Od nieświadomych kroków ludzi zbyt zajętych, by zwracać uwagę na zwykłą cegłę, po gęsty deszcz, który po prostu miał zmoczyć wszystkich.'
    'Te wszystkie zdarzenia nie zostawiły po sobie tylko historii - stały się osadem.'
    'Cienką, kruchą warstwą drobnych rzeczy, które zmieniały tę cegłę, cegła po cegle, krok po kroku.'
    "Patrzysz na małe otwory w cegle, gdy nagle coś zaczyna do ciebie docierać."
    "Cegła sprawia, że czujesz coś, czego wcześniej nie czułeś."
    "Przynajmniej nie w tym mieście."
    "Z powodów, których nie potrafisz wyjaśnić, patrzenie na nią napełnia cię determinacją."
    "Determinacją tak silną, że wszystkie twoje plany, te odkładane w nieskończoność, nagle wydają się nie tylko możliwe, ale konieczne."
    'Nie możesz już zatrzymać tego wiru myśli, który ta starożytna architektura wywołała w twojej głowie, więc wydajesz z siebie długie, dramatyczne westchnienie.'
    'Chcesz, by każda inna cegła w tej przytulnej kawiarni wiedziała, że rozumiesz jej historię.'
    'Ta cegła i jej przeszłość inspirują cię, by iść dalej i się nie poddawać.'
    'Dla zwykłej osoby to była zwykła cegła, ale twoje oczy widzą coś innego - źródło inspiracji i determinacji w tak prostym obiekcie.'
    "Helen Keller powiedziała kiedyś - \"Alone we can do so little; together we can do so much\" - i nic lepiej nie opisałoby tej cegły."
    'Cegła była częścią czegoś większego, bardziej monumentalnego, choć nie wiesz czego.'
    'Cegły mogą być używane do budowania wszystkiego - od małego muru podczas protestu w Paryżu po wielką willę zdolną przetrwać tornado.'
    'Tak jak jedna z tych cegieł, ty również jesteś częścią tego miasta.'
    'Miasta, które przyjęło cię z otwartymi ramionami.'
    r "Jezu, mam go dość, on tak mnie irytuje."
    you "Nie dziwię ci się."
    r "..."
    r "No dobra, co tam chciałeś?"
    "Zapomniałeś o jedzeniu przez to, co się właśnie wydarzyło."
    you "Poproszę 3 buły Rafała."
    r "Jasne."
    r "Ale czekaj, nie widziałem cię wcześniej?"
    r "Nie pracujesz przypadkiem na drugim końcu miasta?"
    wp "No właśnie, też mi się tak wydawało."
    you "Nieee, jestem tutaj nowy."
    you "Urodziłem się wczoraj, jak Konrad."
    "Rafał uważnie cię słucha, wkładając buły do papierowej torebki."
    r "Aha, ma sens."
    you "Widzę, że masz plakaty Taylor Spit."
    r "Znasz ją?"
    you "Tak. Kojarzę ją."
    r "Wow! Ale heca."
    "Wyciągasz bułę Rafała i zaczynasz ją jeść."
    "Ale nie tak normalnie, jakbyś jadł kajzerkę z Biedronki."
    "Tylko jak jakiś homofob jedzący banana."
    "Odrywasz pierwszy kawałek buły ręką i Rafał patrzy się na ciebie, jakbyś popełnił zbrodnię."
    r "Co ty robisz..."
    you "W sensie?{w=.6} Jem."
    r "Nie umiesz w savoir vivre..."
    you "Co???"
    r "Daj mi to. Pokażę ci, jak to się je."
    "Rafał gryzie tę bułkę jak normalna osoba."
    r "No, teraz mam nadzieję, że umiesz."
    r "A tak na marginesie, za dużo soli wsypałem do ciasta."
    you "Imo jest smaczna."
    you "Lubię sól."
    you "Masz jakieś wersje tej buły, czy tylko takie common jak jajo w Adopt Me?"
    r "No, mam tylko takie zwykłe, bo nie mam pomysłu."
    you "Hmmm"
    you "No właśnie, ta z solą jest dobra, więc tych na pewno musisz więcej zrobić."
    wp "Czy ty już kiedyś jadłeś bułę Rafała?"
    you "Tak. Filip mi dał, bo byłem głodny."
    wp "Ma sens."
    r "Okej, dobra, masz fajną aurę. Chcesz z nami wypić trochę herbaty?"
    you "Oczywiście!!"
    "Rafał znika w kuchni, ale szybko wraca z kubkami i cukrem."
    r "Usiądźcie, proszę."
    you "Wy się znacie?"
    wp "Tak. Poznałam go w tej piekarni."
    r "Wyczułem dobry vibe od niej, macie podobną aurę."
    you "{i}Oby nie zieloną!!!{/i}"
    "Rafał podchodzi do drzwi i zamyka je na klucz, sprawdzając, czy nikt nie idzie."
    "Jeszcze raz idzie do kuchni, ale tym razem przynosi gorącą wodę i matchę."
    r "Czekaj, bo zapomniałem cię zapytać."
    r "Co ty chcesz do picia?"
    you "A co tu przyniosłeś?"
    r "Matchę."
    you "KOCHAM MATCHĘ."
    wp "Matching!!!"
    "Przesuwasz się trochę bliżej ściany, żeby ktoś mógł usiąść obok ciebie."
    you "A WIĘC..."
    you "Spill the {i}tea{/i}"
    "Oboje zaczynają się śmiać."
    r "Okej dobra to ja zacznę."
    r "Mam taką herbatę"
    r "Nad tą piekarnią mieszkają ludzie, co nie?"
    r "A więc..."
    r "Wczoraj nie miałem dużo klientów i było cicho."
    r "I teraz uwaga."
    r "Słyszałem, jak jakaś pani kłóciła się ze swoim mężem."
    wp "CO..."
    r "Tak się darli, że to szok!"
    wp "Co ta żona mówiła?"
    r "No dobra, cicho wrócę do tego."
    r "Okazuje się, że ten mąż ją zdradzał."
    r "Z tym typem, który zbiera podatki."
    r "On się tłumaczył, że zrobił to, żeby tych podatków nie płacić."
    menu:
        "Zgadzam się z żoną":
            you "Ale to nie można tak..."
            you "Jak to można tak zdradić?"
            you "Masakra."
            wp "Szczerze to valid crashout."
        "Zgadzam się z mężem":
            you "Może naprawdę są biedni?"
            you "Wtedy {b}MOŻE{/b} zrozumiem."
            you "Nie zrobił tego tak dla fabuły..."
            r "No właśnie zrobił to dla fabuły."
            r "Bo mu się nudziło!"
    r "Co gorsza, znam ich..."
    r "Ta żona jest siostrą babci brata kuzynki siostry mojej koleżanki z byłej pracy."
    you "No..."
    you "To jest trochę szalone{w=.3}, że takie rzeczy się dzieją w tym mieście."
    r "Uwierz mi, są gorsze plotki."
    "Mimo że bardzo interesują Cię plotki, dzisiaj dajesz im spokój."
    wp "Dobra, teraz ja!"
    "Wiktoria pochyla się bliżej ciebie."
    wp "Nie chcę brzmieć jak Niuniuś, którego Rafał pobił miotłą, ale...{w=.3} muszę zapytać."
    "Wiktoria pochyla się {b}JESZCZE{/b} bliżej ciebie."
    wp "Czy ty też uważasz, że to miasto coś ukrywa?"
    "Nie zajmuje ci dużo czasu, żeby odpowiedzieć na to pytanie."
    "Od kiedy Kurowska opowiedziała ci o tym mieście, wiedziałeś, że coś jest nie tak."
    "Trudno powiedzieć, czy to była twoja inteligencja{w=0.5}, czy po prostu jesteś normalnie taki podejrzliwy wobec wszystkiego."
    you "No tak."
    you "Imo to miasto ogólnie jest dziwne."
    you "Na przykład, czemu to miasto leży w jakimś losowym mieście?"
    you "I dlaczego tu jest tylko jedno miasto?"
    you "Ja mam uwierzyć w to, że nikomu nie chciało się osiedlić gdzieś indziej?"
    wp "NO WŁAŚNIE."
    if knowsAboutVasiliGrandfatherGhost:
        you "Dowiedziałem się od Vasiliego, że to jezioro jest jakieś magiczne."
        you "Bo pojawia się tam duch jego dziadka."
    if metWiktoriaP:
        you "Od ciebie też dużo się dowiedziałem."
        "Patrzysz się na Wiktorię."
    if seenBjorkGhost:
        you "Poza tym widziałem dusze Bjork."
    you "Dziwne to wszystko."
    wp "WIDZISZ RAFAŁ!!!"
    wp "Mówiłam ci."
    r "No dobra, powiedzmy, że masz rację."
    r "I co teraz?"
    wp "Nie wiem, ale..."
    wp "Trzeba coś zrobić po prostu."
    you "No rel."
    you "Jest może jakieś muzeum w tym mieście?"
    wp "No jest. To jest ten kościół."
    you "No to idziemy tam."
    wp "Okej."
    wp "Mogę jutro o 10:00."
    you "No to spotykamy się na rynku o 10:00."
    wp "Dobra."
    r "A ja, to co?"
    wp "Ale czy ty chcesz z nami iść do kościoła?"
    r "Nie."
    wp "No właśnie."
    you "Dobra, to wiecie co.."
    you "Dziękuję za herbatę, jesteście mega fajni."
    you "Ale ja muszę iść."
    you "Popatrzę się jeszcze raz na tę fontannę na rynku i pójdę do krawcowej."
    you "Bo nie mam żadnych ubrań."
    wp "Paaa"
    r "Do widzenia, senorita."
    you "{i}Jestem dumny z siebie.{/i}"
    you "{i}Chyba znalazłem besties w tej piekarni!!!{/i}"
    scene bg bakeryfrontday with dissolve
    "Wychodzisz i idziesz prosto do tej fontanny."
    "Na szczęście miejsce docelowe jest blisko."
    scene bg fountainday with dissolve
    stop music fadeout 5
    "Powietrze dalej jest gęste przy tej fontannie."
    "Patrzysz się na tę fontannę inaczej, ponieważ już wiesz, że coś jest nie tak."
    "Analizujesz każdy centymetr kwadratowy tej fontanny jak teksty piosenek."
    "W końcu twój wzrok pada na napis w obcym języku, którego wcześniej nie widziałeś."
    you "Co za dziad to pisał..."
    show bjork normal with dissolve
    if seenBjorkGhost:
        you "Znowu ty."
    else:
        you "Hejka?"
        you "Czekaj, czy ty nie jesteś Bjork przypadkiem?"
        bjork "Jestem."
        you "Omg, widziałem twój portret."
    "Jesteś w szoku, że widzisz duszę Bjork przed sobą."
    "Nikt inny na rynku pewnie tego nie widzi, ponieważ nikt na to nie reaguje."
    "Wygląda, jakbyś miał schizofrenię przez to, że gadasz do fontanny."
    bjork "{i}Underneath our feet{/i}"
    bjork "{i}Crystals grow like plants{/i}"
    bjork "{i}Listen how they grow{/i}"
    you "Czekaj tu, ja zaraz wrócę."
    bjork "Nie ufaj w{w=0.5}.{w=0.5}.{w=0.5}.{nw}"
    play sound "sfx_footsteps_a.mp3"
    scene bg bakeryfrontday with dissolve
    "Biegniesz z powrotem do piekarni, żeby powiedzieć Rafałowi i Wiktorii o tym, co właśnie zobaczyłeś."
    "I tak ci pewnie nie uwierzą, ale musisz spróbować."
    "Wiesz, jest duża szansa, że będziesz wyglądał jak idiota, jeśli na serio tylko ty możesz widzieć Bjork."
    "Bo jak nie, to serio masz schizofrenię."
    scene bg bakeryinside with vpunch
    you "Duch Bjork jest przy fontannie."
    with vpunch
    play sound "sfx_footsteps_alot.mp3"
    "Wiktoria nie traci ani sekundy i wybiega z piekarni."
    with vpunch
    play sound "sfx_footsteps_alot.mp3"
    "Rafał biegnie za Wiktorią, nawet nie zamykając piekarni."
    play sound "sfx_footsteps_b.mp3"
    scene bg fountainday with dissolve
    show wp normal at leftish with moveinleft
    show rafal normal at rightish with moveinleft
    r "Nikogo tu nie ma."
    you "Ona zrobiła ze mnie idiotę."
    you "Zrobiła ze mnie idiotę jak w jakimś stereotypowym filmie o duchach."
    r "Nie wiem czy Wiktoria ci wierzy, ale ja tak."
    r "Na pewno coś widziałeś."
    r "..."
    you "I co teraz?"
    wp "Nie wiem."
    r "Nie wiem."
    you "Bjork pewnie nas podsłuchiwała w tej piekarni."
    you "{i}Jeśli ty to słyszysz, proszę mnie nie nawiedzać.{/i}"
    you "{i}Bo nie wytrzymam.{/i}"
    "Patrzycie się na tę fontannę, ale nic dziwnego się nie dzieje."
    r "Dobra, ja chyba wracam."
    wp "No, ja już też idę."
    you "Naprawdę przepraszam, że was tak oszukałem trochę."
    wp "Ok."
    you "No to cześć."
    r "Cześć siedem!!!"
    jump t_GoingToTheTailor

label t_GoingToTheTailor:
    play music "town_day.mp3"
    "Tym razem idziesz prosto do krawcowej."
    "Bez żadnych duchów lub jakiejś fontanny."
    "Na szczęście to nie było trudne, bo krawcowa jest tuż obok piekarni."
    "Jej sklep wygląda tak ostentacyjnie, że aż stoisz i się gapisz."
    "Jest pięknie."
    "Kiedy w końcu się ogarniasz, wraca ci logiczne myślenie i zaczynasz myśleć o cenach."
    "Raczej nie masz tyle kasy, żeby coś kupić w takim miejscu."
    "Jednakże, wchodzisz do środka i się rozglądasz."
    "Wszystko jest zastawione pięknymi sukienkami, koszulami, spodniami i innymi ubraniami, których nazw nie znasz."
    "Odwracasz głowę i widzisz zwykłe białe koszule i nudne spodnie, które bardziej pasują do twojego budżetu."
    "Wtedy słyszysz głos kobiety z kąta. To była krawcowa."
    "Na początku jej nie zauważyłeś przez te wszystkie kolorowe ubrania wokół niej."
    you "{i}Idealny kamuflaż{/i}"
    m "Dzień dobry!"
    you "Dzień dobry!"
    you "Nazywam się [name] i jestem nowy w tym mieście."
    m "Masz fajne imię."
    you "A dziękuję, dziękuję."
    m "Czy Pan czegoś szuka?"
    you "Proszę mówić do mnie na \"ty\"."
    you "To nie jest LinkedIn."
    m "Aha dobra."
    you "Kropki też w sumie nie są potrzebne bo wygląda jakbyś była zła na mnie"
    # TODO: Koniec na dzisiaj ― maksym te kropki!!!
    ww "Ok"
    you "A jak ty masz na imię"
    ww "Wiktoria"
    you "Omg już znam jedną"
    ww "No ja też my się znamy"
    ww "W tym mieście są tylko dwie"
    you "Jednak małe jest to miasto wszyscy się znają"
    you "Podoba ci się tu?"
    ww "Jak się nie ma co się lubi to się lubi co się ma"
    you "Ma sens"
    ww "No to dobra czy ty czegoś szukasz??"
    you "Na razie tylko się patrzę bo nie wiem czy mam pieniądze na takie ubrania"
    you "Są piękne i w tym jest problem"
    ww "Dobra to podejdź do mnie jak coś znajdziesz"
    "Krawcowa wraca do swojego stołu i zaczyna rysować kobiętę w swoim zeszycie."
    "W tym samym czasie masz dylemat, ponieważ nie wiesz, co masz kupić."
    "Więc chodzisz po tym sklepie i się tylko gapisz na wszystkie tekstylia"
    "Są przynajmniej dwa powody, dla których nie wiesz, co kupić"
    "Pierwszy jest najprostszy. Nie wiesz czy te ubrania są drogie czy tanie"
    "Mieszkasz w tym mieście tylko dzień, więc nie rozumiesz ich waluty"
    "Po drugie, nie wiesz czy będziesz pasował do reszty mieszkańców"
    "Nie zwracałeś uwagi na to, co noszą mieszkańcy tego miasta"
    "Ale jesteś zbyt leniwy, aby wyjść ze sklepu"
    "Na Temu można kupić kostium dużej kaczki, ale żaden psychicznie zdrowy człowiek nie wyjdzie w tym na rynek"
    "Patrzysz się przez okno aby kogokolwiek zobaczyć ale jest już za ciemno"
    "Światło ze sklepu odbija się w oknie, przez co kompletnie nie widać ulicy"
    "Długo chodzisz po tym sklepie i przypadkiem wchodzisz do pokoju z napisem 'burżuazja'"
    "W tym sklepie są identyczne ubrania, tylko że ceny są liczbami z zakresu <100,000; +9,223,372,036,854,775,807>"
    "W rzeczywistości stoisz przed jedną z tych sukienek."
    "Sukienka przed tobą nie wygląda nie na miejscu w tym sklepie, a jednak jej cena jest najwyższą liczbą, jaką kiedykolwiek widziałeś."
    "Jej cena jest tak wysoka, że zostały użyte potęgi, aby ją zapisać"
    "Wychodzisz z tego pokoju, ponieważ gdybyś coś zepsuł to byś musiał pracować całe życie, żeby spłacić 1% długu"
    "W tym momencie chodzisz po sklepie już od godziny i znów jesteś w punkcie wyjścia: nie wiesz, co kupić"
    "Podchodzisz do krawcowej, aby poprosić ją o pomoc i widisz piękną kobietę w jej zeszycie"
    you "Czy mogłabyś mi pomóc??"
    you "Nie wiem co kupić"
    ww "Już"
    "Krawcowa wstaje i podchodzi do ciebie i zaczyna chodzić wokół ciebie"
    "Wyciąga metr aby zmierzyć twojego skinny waista"
    if hasSkinnyWaist:
        ww "To jest niemożliwe"
        ww "Twój skinny waist ma 3 centymetry"
    else:
        ww "Ale masz skinny waista"
    you "Właśnie w tym jest problem bo nie mogę nic wybrać"
    ww "A co byś chciał"
    you "Na pewno chcę wyglądać normalnie"
    you "Normalnie w sensie jak każdy inny mieszkaniec tego miasta"
    "Krawcowa kładzie swoją rękę na żuchwę, robiąc taki gest aby pokazać ci że intensywnie myśli o tym, w co może cię ubrać"
    ww "Dobra wiem. Stój tu grzecznie ja zaraz wrócę."
    "Wiktoria zostawia ciebie przed lustrem i gdzieś idzie"
    "Znowu się patrzysz na te proste ubrania dla biednych ludzi"
    "I już czujesz ten wstyd"
    "Po chwili wraca Wiktoria z ubraniami i jakimś pudełkiem"
    "Wiktoria zostawiła pudełko na podłodze, aby pokazać ci twoje nowe ubrania"
    "Pokazuje ci niebieskie jeansy i białą koszulkę"
    you "{i}Niebieskie dżinsy, biała koszula...{/i}"
    you "{i}Weszłaś do pokoju, wiesz, że aż zapiekły mnie oczy{/i}"
    "Przykładasz do siebie najpierw koszulę a potem jeansy"
    you "Fajnie"
    you "Mi się podoba"
    you "Wyglądam tak, wiesz, normalnie"
    ww "A teraz daj mi to i weź to"
    "Wiktoria daje ci jakieś inne ubrania"
    "Tym razem daje ci czarną sukienkę, czarną koszulkę i duży czarny melonik"
    you "Nie"
    "Nawet nie przykładasz tego do siebie, ponieważ wiesz, że nigdy nie będziesz wyglądał jak Zendaya"
    "Poza tym, już wiesz co będziesz kupował"
    you "Zapytam się wprost"
    "Wkazujesz pazurem na jeansy z białą koszulką"
    you "Ile to kosztuje?"
    ww "To wszystko czy tylko te ubrania"
    you "Jak to wszystko? To pudełko też?"
    ww "Tak ale do tego wrócę"
    ww "Same te ubrania kosztują 150 foryntów"
    you "Myślałem, że w tym sklepie zbankrutuję"
    you "Mam tylko 670"
    ww "Starczy ci na parę dni."
    ww "Mówiłeś że jesteś tutaj nowy co nie?"
    you "No tak"
    ww "Okej to polecam zostawić 100 foryntów"
    ww "Ponieważ jutro pan Antoni będzie zbierał podatki"
    you "Skąd wiesz"
    ww "On zbiera podatki co tydzień w sobotę"
    you "Aha ma sens"
    you "{i}Czyli dzisiaj jest piątek...{/i}"
    you "Dobra to wracając do tych tekstyliów"
    you "Mi się podoba"
    ww "Cieszę się"
    you "A teraz co to za pudełko"
    ww "To jest taki starter pack"
    ww "Tam są majtki, skarpetki i inne rzeczy do higieny"
    ww "A i właśnie"
    ww "Tych ubrań, majtek i skarpetek nie trzeba prać"
    you "Jak to?"
    ww "Srak to"
    ww "Poprosiłam Piotra aby mi wynalazł magię na to"
    ww "No i od teraz ubrania są magiczne i wgl"
    "Te ubrania są magiczne specjalnie"
    "Bo nie chce mi się opisywać jak robisz pranie"
    you "Okej..."
    you "Ile to wszystko kosztuje?"
    ww "180 foryntów"
    you "Proszę"
    "Płacisz za wszystko, uśmiechając się do sprzedawczyni"
    "Widzisz słoik z napisem 'nawodnik (nie napiwek bo ne piję piwa tylko wodę)'"
    "Czy chesz wrzucić parę monet do tej puszki"
    menu:
        "Tak":
            "Wrzucasz resztę z swoich zakupów do tego słoika"
            ww "Thank you thank you thank you"
            "Wiktoria uśmiecha się jak w reklamie nieruchomości"
        "Nie":
            "Nie wrzucasz nic, ponieważ słuchasz chopbra, melanie oraz shitseye"
    you "Dziękuję!!"
    you "A właśnie mam pytanie"
    ww "Słucham"
    you "Widziałem sukienkę która kosztuje 3.5341*10^(67) foryntów. Czy ktoś w tym mieście naprawdę ma tyle pieniędzy?"
    ww "Nie"
    ww "Jeśli ktoś chce takie coś kupić to robię im zniżkę o wielkości 100%-(7.931345876241576*10^-131)%"
    ww "Żeby się zaprzyjaźnić z tą bogatą osobą"
    you "Ma sens"
    "Patrzysz się na tą sukienkę jeszcze raz, i teraz wiesz, że nie jest tyle warta, mimo tego, że jest piękna"
    you "Będę to nosił loud and proud"
    ww "Cieszy mnie to"
    you "Dobranoc!!"
    ww "Sayonara"
    "Po raz ostatni uśmiechasz się jak w reklamie nieruchomości i wychodzisz ze sklepu"
    "Jest już noc, i tym razem nie chcesz szwędać po mieście"
    "Więc wracasz do domu."
    jump t_goingHomeAfterTailorSecondDay


label t_goingHomeAfterTailorSecondDay:
    "Wychodzisz ze sklepu ale na zewnątrz już jest noc"
    "Zastanawiasz się jakim cudem spędziłeś tyle czasu u krawcowej"
    "Ale to bylo tego warte, ponieważ masz już wszystko aby zacząć tu mieszkać"
    "Masz jedzenie, ubrania, pieniądze i nawet własny dom. Czego więcej można chcieć?"
    "Robisz 2 kroki do przodu kiedy widzisz przed sobą kościół"
    "Oraz osobę, która zamyka drzwi do tego kościoła, a potem bramę na klucz"
    "Nie wiesz kim jest ta osoba, ale jesteś na 99%% pewny, że to jest ksiądz"
    if receivedLoreAboutChurchOnTheFirstDay:
        you "{i}Jakim cudem Wiktoria otworyła tę bramę,{/i}"
        you "{i}jeśli on zamyką ją na klucz?{/i}"
        you "{i}To chyba Wiktorii nie mogę ufać{/i}"
        you "{i}Po co jej tyle powiedziałem...{/i}"
    "Patrzysz na swoje nowe ubrania, żeby nie zwracać na siebie uwagi"
    "Ale tak naprawdę patrzysz się na tego księdza widzeniem peryferyjnym"
    "Kiedy ten mężczyzna jest wystarczająco daleko od kościoła, podchodzisz do niego bliżej."
    "Jutro będziesz tu z Wiktorią"
    "Najpierw patrzysz na niedawno zamknięte drzwi, potem na ogromny witraż"
    "Następnie delikatnie dotykasz bramy i czujesz, jak bardzo jest zakurzona, mimo że jest używana codziennie."
    "Teraz ten kościół jest zamknięty, więc nie możesz wejść do środka"
    "Z powodu braku rzeczy, które możesz teraz zrobić, idziesz do domu"
    "Gdzieś w połowie drogi masz takie przeczucie, że ktoś cię obserwuje"
    "Powietrze wokół ciebie robi się trochę chłodniejsze. Na tyle, że to zauważasz" 
    "Przez chwilę nie wiesz, co powinieneś zrobić: biec do domu, czy iść, jakby nic się nie działo."
    "Nie jesteś pewien, czy w tej chwili jesteś delulu, ale potem przypominasz sobie, gdzie mieszkasz."
    "Istnieje magia, co oznacza, że prawie na pewno czujesz, że ktoś cię obserwuje."
    "Odwracasz się w taki sposób, aby pokazać, jak bardzo się 'nie boisz',"
    "ale w głębi duszy masz nadzieję, że twoje oczy spotkają ptaka lub przypadkowego gryzonia."
    "Jednak nikogo nie ma. Nie można tego powiedzieć o twoim uczuciu, które wciąż tu jest,"
    "teraz silniejsze dzięki temu, że nie wiesz, gdzie jest twój 'szpieg'."
    "Odwracasz się i idziesz, jakby nic się nie stało."
    "Uczucie w końcu ustaje, gdy wchodzisz do domu i zamykasz drzwi."
    "Na wszelki wypadek zamykasz wszystkie rolety."
    "Odkładasz buły Rafała do lodówki."
    you "{i}Mam nadzieję, że ten krasnal nie zje tych buł{/i}"
    you "{i}Czy ja go musze karmić??{/i}"
    you "{i}Czy on jest jakimś szkodnikiem{/i}"
    you "Cześć?"
    "Ten krasnal kompletnie ignoruje to, co do niego powiedziałeś"
    "Jest skupiony tylko na światełku w tej lodówce"
    "Z tej racji zamykasz lodówkę i kładziesz się spać"
    jump h_wakingUpSecondNightAtHome

label t_goingToTownBecauseYouAreGoingToTheLocalChurchSecondDayWaitNoItIsTheThirdDayNevermind:
    "Pędzisz na rynek, jedząc po drodze jedyne jedzenie, jakie masz."
    "Kiedy tam docierasz, widzisz stojącą tam Wiktorię."
    wp "O hejka"
    you "Cześć"
    wp "..."
    you "Dobra chodźmy do tego kościoła"
    wp "Dobra"
    you "Widziałem tego księdza wczoraj"
    you "Chyba księda"
    you "Nie jestem pewny"
    you "Wychodził wczoraj z kościoła"
    wp "No to na pewno był ten ksiądz"
    wp "Ma na imię Wiesław"
    wp "Ale wszyscy mówimy na niego wsiok bo tak się zachowuje"
    you "Jak?"
    wp "On jest jak osa. Osy tylko latają i żądlą"
    wp "Tak jak on tylko pracuje w tym kościele i je"
    wp "Przy ołtarzu jest cały święty, a w piątek po południu pewnie pije w domu"
    "Podchodzicie do bramy i Wiktoria wsadza rękę przez pręty bramy i otwiera ją od środka."
    if metTomcio:
        "Tak jak ty otworzyłeś bramę Tomcia"
    you "Czekaj jak on ma na imię?"
    wp "Wiesław."
    you "{i}Jego imię też jest na W{/i}"
    you "{i}Znam już 3 takie osoby{/i}"
    you "{i}To komu ja w końcu mam nie ufać{/i}"
    you "Po co otworzyłaś bramę? Można bylo przejść tam"
    "Wskazujesz pazurem na furtkę"
    wp "Aha ja tego nie widziałam"
    you "Tak szczerze to ja też dopiero teraz to zauważyłem"
    "Oboje śmiejecie się z tego"
    wp "Dobra cicho!"
    wp "Bo wyjdzie zaraz"
    wp "Chodź"
    "Wiktoria podchodzi do drzwi i delikatnie puka"
    "Po chwili słychać czyjeś mamrotanie po drugiej stronie drzwi"
    "Otwiera się takie mini okienko i po drugiej stronie tych drzwi widać tylko parę oczu"
    "Takie mini okienko w sensie no"
    "Według googla to się nazywa judasz ale nie wiem do końca czy to jest to"
    "Bo to jest dosłownie takie okienko ale no"
    "Więc niech tak zostanie"
    "Te oczy patrzą najpierw na Wiktorię, potem na ciebie."
    "Wiesław westchnął, jakby Wiktoria poprosiła go o 1000 foryntów"
    w "Co?"
    "Widać, że nawet Wiktoria, która od wielu lat tu mieszka, nie chce z nim rozmawiać"
    wp "Mamy nowego mieszkańca Bratgren i chcę mu wszystko pokazać"
    wp "Czy możemy wejść"
    w "Mamy świeżą krew..."
    w "Trzeba było tak od razu mówić"
    you "{i}Czy on jest głupi? Przecież od razu powiedziała..{/i}"
    w "W takim razie zapraszam..."
    you "{i}Syczy niektóre słowa tak, że teraz bardziej wygląda na węża niż na to, czymkolwiek on jest.{/i}"
    "Ostrożnie wchodzicie do środka..."
    w "Czy mogę zaoferować Ci {i}specjalną{/i} wycieczkę po kościele?"
    you "Yyy..."
    "Patrzy się na ciebie z uśmiechem jak w reklamie nieruchomości, tylko ten uśmiech jest taki creepy"
    you "Nie, dzięki."
    you "Wiktoria miała mi pokazać wszystko"
    w "Ale czy ty jej ufasz? Nikt nie opowie ci o historii tego miasta lepiej ode mnie"
    you "Tak"
    w "No dobra..."
    w "W takim razie nie będę przeszkadzał..."
    "Wiesław, na szczęście, zostawia was, a potem znika w przypadkowym pokoju niedaleko ołtarza"
    # PROSZĘ TO TAK ZOSTAWIĆ!!
    # ⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
    you "(szeptem) Czemu on jest taki dziwny??" # ❌❌❌❌do not touch❌❌❌❌❌
    you "(szeptem) Nie mówiłaś mi o tym." # ❌❌❌❌do not touch❌❌❌❌❌
    wp "(też szeptem) No dobra już" # ❌❌❌❌do not touch❌❌❌❌❌
    wp "(szeptem) Chodź ale bądź cicho." # ❌❌❌❌do not touch❌❌❌❌❌
    you "(dalej szeptem) Gdzie mam iść?" # ❌❌❌❌do not touch❌❌❌❌❌
    wp "(chyba nie muszę tu nic więcej pisać) Tu." # ❌❌❌❌do not touch❌❌❌❌❌
    you "(Domyśl się) Ok..." # ❌❌❌❌do not touch❌❌❌❌❌
    # ⬆️⬆️⬆️⬆️⬆️⬆️⬆️⬆️⬆
    # okej dobra
    "Trudno opisać, jak wygląda wnętrze tego kościoła, więc możesz spojrzeć na tło." 
    "Bogactwo, piękno, kunszt wykonania - jest tu wszystko, wszędzie, wszystko naraz."
    "Zaczynasz od kolumn, z których wszystkie były pokryte obrazami, każdy osadzony w złotej ramie z misternymi wzorami."
    "Ten kościół był prawdopodobnie tak stary jak ta cegła w piekarni Rafała." 
    "Tylko że tu ktoś sprząta, dba o ten kościół."
    "Na obrazach była przedstawiona Björk i każdy etap jej życia."
    "Najpierw była jej podróż, potem jak zakładała to miasto, a na końcu jej śmierć"
    "Patrzysz w górę na sufit i widzisz ogromny obraz Björk budującej miasto."
    "Wiktoria zauważa, że stoisz w szoku."
    "Ale kiedy ona też się zatrzymuje, słyszysz, jak cicho jest w tym budynku."
    "Jest tak cicho, że aż robi się strasznie."
    "Na końcu kościoła widzisz ogromną złotą skrzynię ze sztyletem w środku."
    "Przechodzisz obok Wiktorii i podchodzisz do niej bliżej."
    you "Co to jest?"
    wp "To jest ten nóż, którym zabito Bjork."
    if receivedLoreAboutChurchOnTheFirstDay == False:
        wp "Ogólnie to Bjork nie budowała tego miasta sama, bo jej pomagała Sabrina Carpenter"
        wp "To była najlepsza przyjaciółka Bjork i też jakby ironicznie cieśla."
        wp "Zbudowały kilka domów i ludzie zaczęli się pojawiać tak jak ty."
        wp "Do dziś nie wiadomo skąd ci ludzie się biorą."
        you "Nawet Bjork nie wiedziała?"
        wp "Nawet Bjork."
        wp "Jej śmierć była BARDZO tragiczna."
        wp "Była prezydentem tylko 23 lata kiedy sabrina ją zdradziła i dźgnęła nożem."   
        wp "Zginęła w biurze kurowskiej. dokładnie tam gdzie ona teraz siedzi."
        wp "To był tragiczny dzień dla całego miasta."
        wp "No i to jest ten nóż"
    you "..."
    "Patrzysz na nóż i twoja inteligentna głowa od razu zauważa, że coś jest nie tak."
    "Nie chodzi o rękojeść ani sposób wykonania."
    "Nie było to oczywiste, ale to zauważyłeś."
    wp "Co?"
    you "Czy to na pewno jest ten nóż, którym zabito Bjork?"
    you "Tak na 100%%?"
    you "Jesteś tego pewna?"
    w "Czy chcesz powiedzieć, że ta cała historia, włącznie z tym sztyletem jest kłamstwem?"
    "Wiesław pojawia się za tobą, gdy patrzyłeś na nóż." 
    "Żaden z was go nie zauważył, bo chodził bardzo cicho."
    you "Ja... Yyy..."
    w "To.. (kipiący ze złości) To, co właśnie powiedziałeś, można porównać do plucia wszystkim w twarz"
    you "Ale ja nie.. Ale"
    w "Proszę WYjść."
    you "Ale"
    w "NATYCHMIAST"
    "Czujesz, że jeśli teraz nie wyjdziesz, zostaniesz pobity."
    "Widzisz, jak wściekłość narasta w oczach Wiesława z każdą sekundą." 
    "Więc wychodzisz."
    wp "Co to ma być??"
    you "No rel on jest taki niemiły dla mnie."
    wp "Nie. Mówię o tobie." 
    wp "To była twoja jedyna szansa, żeby dowiedzieć się czegoś o tym mieście, a ty ją zmarnowałeś."
    wp "Nigdy nie wpuści tam ciebie i twojej nieufnej dupy."
    "Dramatycznie odwracasz głowę i udajesz, że stoisz z melancholią przed oknem, żeby pomyśleć o swoim następnym kroku."
    "Ze wszystkich znanych ci osób, których imiona zaczynają się na W, najbardziej sus jest Wiesław." 
    "On traktuje tę religię zbyt poważnie."
    you "Nie musi mnie wpuszczać."
    "Otwierasz drzwi, które Wiesław zapomniał zamknąć, i zaglądasz do środka." 
    "Wiktoria widzi, co robisz i jest w szoku, ale nie krzyczy, nie biegnie do rządu, tylko zostaje."
    wp "Ale co ty robisz..."
    wp "Bez jaj.."
    "Bo ona też jest ciekawa tego miasta." 
    "Ostrożnie poruszasz głową."
    "Kiedy Wiesław znów znika w swoim pokoiku, otwierasz drzwi i gestem ręki wskazujesz Wiktorii, żeby poszła z tobą."
    "Podczas gdy ona stara się jak najciszej je zamknąć, ty już jesteś przed tajemniczym pokojem, do którego Wiesław cały czas wchodzi."
    "Widzisz Wiktorię na drugim końcu korytarza, przykładającą pazur do skroni, pokazując, że oszalałeś i ma ciebie dość"
    "Ty jednak to ignorujesz i realizujesz swój plan."
    "Szybko i cicho chwytasz przypadkowe krzesło i blokujesz drzwi, przez które właśnie przeszedł Wiesław."
    "Potem stwierdzasz, że to za mało i chwytzasz pięć kolejnych, tworząc wieżę Eiffla z krzeseł."
    "Następnie gestem ręki wskazujesz Wiktorii, żeby weszła."
    "I ona idzie, kompletnie zszokowana tym, co właśnie zrobiłeś."
    "Wiktoria jest BARDZO bamboozled."
    wp "No ale co ty robisz? Oszalałeś?"
    you "Musiałem to zrobić, okej? To było konieczne."
    wp "Konieczne do czego?"
    you "Nie mogę cię tu zostawić bez pokazania ci tego, co widziałem."
    you "Chodź, spójrz na nóż."
    wp "No i co z nim?"
    you "Spójrz na krew." 
    you "Widzisz, jaka jest jasno czerwona?"
    you "Kiedy krew wysycha, robi się brązowa z powodu zawartego w niej żelaza." 
    you "Ta krew, jeśli w ogóle można ją tak nazwać, nadal jest czerwona, po 400 latach."
    "Twarz Wiktorii zmienia się z \"jesteś szalony\" w \"jednak masz rację\""
    wp "No.... No no no masz rację"
    wp "Że nikt tego nie zauważył wcześniej?"
    you "Ten nóż jest podróbką."
    wp "No dobra, i co teraz?" 
    wp "Prawdziwy nóż może być gdzieś ukryty, a to może być po prostu kopia dla zwykłych ludzi."
    wp "Wiesz o co mi chodzi?" 
    wp "Tę kopię łatwo ukraść. Jestem pewna, że prawdziwy nóż jest chroniony a nie tak jak tu"
    wp "Każdy tu może przyjść i wyjąć ten nóż"
    you "To akurat prawda, ale..."
    you "Możesz nie rozumieć tego jeszcze, ale chodzi mi o coś innego. Ja-"
    "Słyszysz przekręcenie klamki i widzisz, że Wiesław próbuje wyjść."
    wp "On może wyjść przez okno. Musimy uciekać."
    "Wybiegasz z kościoła jak najszybciej, całkowicie ignorując konieczność zachowania ciszy i biegniesz do piekarni." 
    "Biegniesz do piekarni i na szczęście nikogo tam nie ma."
    wp "Rafał, zamknij drzwi. Natychmiast."
    r "Dlaczego?"
    wp "Zamknij je. Natychmiast."
    "Rafał pospiesznie bierze klucze i zamyka drzwi, po czym wypatruje na zewnątrz potencjalnego zagrożenia." 
    "Wiktoria opuszcza rolety, a jej ręce drżą."
    r "Czy powie mi ktoś, co się dzieje?"
    wp "Byłam w kościele z [name]"
    wp "A ten IDIOTA musiał zacząć się drzeć na cały kościół"
    wp "Bo ten nóż niby nie jest prawdziwy i masakra"
    you "Ale on nie jest prawdziwy"
    r "Po czym to poznałeś"
    you "No bo krew po 400 latach jest dalej czerwona a powinna być brązowa"
    wp "Ja nie skończyłam opowiadać."
    wp "[name] zamnkął Wiesława w swoim goon cornerze"
    wp "Wiesz gdzie to jest"
    r "Zartujesz."
    you "Nie-e"
    "Uśmiechasz się jak pick me"
    r "W sumie należało mu się. On mnie irytuje."
    wp "No rel ale i tak to jest szalone"
    you "..."
    r "..."
    wp "Miałeś chyba coś opowiadać, [name]"
    you "Aha no tak"
    you "Pamiętasz jak wczoraj widziałem Bjork?"
    wp "No"
    you "Ona rzeczywiście tam była, tylko uciekła."
    you "Powiedziała mi jakiś wiersz"
    you "{i}Underneath our feet{/i}"
    you "{i}Crystals grow like plants{/i}"
    you "{i}Listen how they grow{/i}"
    you "Ale to już nieważne bo jej druga wypowiedź jest ciekawsza"
    you "Bo jak już biegłem do was, ona zaczęła mówić \"Nie ufaj w...\""
    you "I byłem święcie przekonany, że to tobie nie mogę ufać, bo wtedy tylko twoje imię było na w..."
    you "Ale to chyba Wiesławowi nie mogę ufać."
    wp "Aha..."
    r "Ale czemu ona akurat do ciebie przyszła?"
    you "Nie wiem.. Chyba mam jakiś plot armor."
    wp "..."
    you "Myślałem, że będziesz na mnie zła"
    wp "Gdybym była tobą, to bym to samo zrobiła."
    r "Mam pomysł"
    r "O której Wiesław wychodzi z tego kościoła?"
    you "O 19:00"
    r "Możemy się włamać do tego kościoła"
    you "O tak"
    wp "Jesteście durni..."
    r "Nie"
    you "To jest świetny pomysł"
    you "Nikt nas nie przyłapie na tym i będzie git"
    wp "Ten pomysł to jest najgłupszy pomysł kropka"
    r "No ale jak ty chcesz dowiedzieć się czegoś nowego"
    r "Nie możemy z tym pójść do Kurowskiej"
    r "Co jeśli ona maczała w tym palce"
    wp "Masz rację"
    you "..."
    you "Która jest godzina?"
    r "YYyy.... 12:00 a co?"
    you "No to trzeba się przygotować jeśli rzeczywiście chcemy tam się włamać"
    you "Mamy 7 godzin"
    you "Czekaj jak my otworzymy drzwi"
    you "Wiktoria może otworzyć bramę. Ale co z drzwiami?"
    r "Chodzę na pilates"
    you "No i co w związku z tym?"
    r "Mam tak wielką dupę, że mogę na nią skoczyć i zrobić trzęsienie ziemi."
    r "Tym otworzymy drzwi"
    "Jest ci ciężko w to uwierzyć, ale Rafał jest tak pewny swojego pomysłu, że to powinno się udać"
    you "Ok"
    wp "Ok"
    wp "To w takim razie co robimy"
    you "Możemy iść do biblioteki"
    r "A potem co? Mamy 7 godzin"
    you "Sybau coś wymyślimy"
    you "To na co czekamy?"
    r "W pół do komina"
    you "No ale chodź no"
    "Rafał otwiera drzwi i wszyscy wychodzą z piekarni, a po zamknięciu piekarni idziecie do tej biblioteki"
    you "{i}Dobrze, że to miasto nie jest duże{/i}"
    you "{i}Wszystko jest bardzo blisko{/i}"
    "Wszystko w tym mieście rzeczywiście jest blisko."
    "Nie mnie to oceniać, czy to przez to, że miasto jest naprawdę małe, czy przez to, że wszystko jest na rynku"
    "Znasz osoby, które nie są w stanie przejść trzech kilometrów"
    jump t_GoingToTheLibrary

label t_GoingToTheLibrary:
    "Na pierwszy rzut oka budynek przed tobą nie wygląda na bibliotekę." 
    "Jedyne, co go zdradza, to napis \"biblioteka publiczna\" na drzwiach."
    you "Nigdy tu nie byłem"
    r "No co ty nie powiesz"
    you "DOBRA CICHO BĄDŹ"
    you "Lets go girls"
    "Okazuje się, że ta biblioteka jest większa, niż się wydawało z zewnątrz."
    you "Dzień dobry!"
    m "Dzień dobry."
    you "Nazywam się [name] i mieszkam tu od 2 dni. Szukam informacji o tym mieście"
    b "Ja mam na imię Bartosz, a książki o Bratgrenie, których potrzebujesz, znajdują się na półce nr 2"
    "Patrzysz się dookoła, i widzisz, że obok ciebie jest półka nr. 2367"
    "Odwracasz się do Rafała i Wiktorii, i mówisz do nich, zdruzgotany"
    you "Jak duża jest ta biblioteka"
    you "Gdzie są te książki"
    wp "Ale skąd ja mam wiedzieć, ja tu nigdy nie byłam"
    r "To się zapytaj"
    "Odwracasz się do Bartosza i uśmiechasz się jak 9/10 dentystów w reklamie pasty do zębów"
    "Nie musisz nawet zadawać pytania, ponieważ Bartosz wszystko słyszał"
    b "Tu idziesz prosto, do końca korytarza."
    b "Potem, idź w lewo i dalej prosto"
    b "Po prawej stronie będziesz miał półki. Znajdź półkę 14856"
    b "Kiedy ją znajdziesz idź tam, dalej prosto, i po lewej będziesz miał schody"
    b "Idź 40 schodek do góry (nie więcej)"
    b "Potem idź 50 kroków na wschód i idź 3 schodki w dół"
    b "Przejdź obok naruszenia zasad BHP, a półka, której potrzebujesz, będzie po prawej stronie"
    b "Tu masz mapę"
    "Bartosz daje ci zwiniętą karteczkę wielkości prostopadłościanu o wymiarach 10cm, 6cm, 0.4cm, ale kiedy ją rozwijasz staje się tak wielka jak ty"
    you "Dziękuję..."
    "O dziwo, dojście do tej półki zajęło wam jakieś 3 minuty"
    "Ale wywróciłeś się na schodach, więc teraz boli cię stopa"
    you "Ale dużo tu tych książek o Bratgrenie"
    you "Patrzcie. Tu nawet jest coś dla dzieci"
    "Wyciągasz \"Opowieści z Bratgren\""
    menu:
        "CZYTAMY":
            ""

        "Nie":
            "Ale jesteś nudny"




